// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/generic.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *structpb.Struct       `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"` // JSON-like structure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericRequest) Reset() {
	*x = GenericRequest{}
	mi := &file_proto_generic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)  
	
}

func (x *GenericRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRequest) ProtoMessage() {}

func (x *GenericRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRequest.ProtoReflect.Descriptor instead.
func (*GenericRequest) Descriptor() ([]byte, []int) {
	return file_proto_generic_proto_rawDescGZIP(), []int{0}
}

func (x *GenericRequest) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_proto_generic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_proto_generic_proto_rawDescGZIP(), []int{1}
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_generic_proto protoreflect.FileDescriptor

const file_proto_generic_proto_rawDesc = "" +
	"\n" +
	"\x13proto/generic.proto\x12\agateway\x1a\x1cgoogle/protobuf/struct.proto\"=\n" +
	"\x0eGenericRequest\x12+\n" +
	"\x04body\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04body\"+\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2W\n" +
	"\x0eGenericService\x12E\n" +
	"\fHandleStream\x12\x17.gateway.GenericRequest\x1a\x18.gateway.GenericResponse(\x010\x01B\vZ\t./gatewayb\x06proto3"

var (
	file_proto_generic_proto_rawDescOnce sync.Once
	file_proto_generic_proto_rawDescData []byte
)

func file_proto_generic_proto_rawDescGZIP() []byte {
	file_proto_generic_proto_rawDescOnce.Do(func() {
		file_proto_generic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_generic_proto_rawDesc), len(file_proto_generic_proto_rawDesc)))
	})
	return file_proto_generic_proto_rawDescData
}

var file_proto_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_generic_proto_goTypes = []any{
	(*GenericRequest)(nil),  // 0: gateway.GenericRequest
	(*GenericResponse)(nil), // 1: gateway.GenericResponse
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_proto_generic_proto_depIdxs = []int32{
	2, // 0: gateway.GenericRequest.body:type_name -> google.protobuf.Struct
	0, // 1: gateway.GenericService.HandleStream:input_type -> gateway.GenericRequest
	1, // 2: gateway.GenericService.HandleStream:output_type -> gateway.GenericResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_generic_proto_init() }
func file_proto_generic_proto_init() {
	if File_proto_generic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_generic_proto_rawDesc), len(file_proto_generic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_generic_proto_goTypes,
		DependencyIndexes: file_proto_generic_proto_depIdxs,
		MessageInfos:      file_proto_generic_proto_msgTypes,
	}.Build()
	File_proto_generic_proto = out.File
	file_proto_generic_proto_goTypes = nil
	file_proto_generic_proto_depIdxs = nil
}
