name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build binary
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "Building for tag: $TAG_NAME"
        make build

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: gateway-${TAG_NAME}
        path: ./build/gateway
