name: Build and Release

on:
  push:
    # Trigger the workflow on a push to the `main` branch or when a tag is created
    branches: 
      - "main"
    tags:
      - "v*"  # This will trigger for tags that start with "v" (e.g., v1.0, v1.1)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build binary
      run: |
        TAG_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')
        echo "Building for tag: $TAG_NAME"
        make build

    - name: Upload binary as artifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v3
      with:
        name: gateway-${GITHUB_REF##*/}
        path: ./build/gateway  # Replace this with the actual path to your binary
